# 项目相关配置
spring:
  application:
    name: nezuko
  profiles:
    active: dev

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: lunaticf.nezuko
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

logging:
  config: classpath:logback.xml
