# 开发环境配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: lcf14196211
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /sys/druid/*
        login-password: druid
        login-username: druid
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/sys/druid/*"
        url-pattern: /*
      max-active: 20
      max-wait: 60000
      filter:
        stat:
          slow-sql-millis: 3000
          log-slow-sql: true
          merge-sql: true
        wall:
          db-type: mysql

server:
  port: 80
